# Generated by Django 5.1.2 on 2024-11-22 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_orden_numero_recibo_alter_detalleorden_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='numero_recibo',
            field=models.CharField(default=uuid.uuid4, max_length=20, unique=True),
        ),
    ]
