# Generated by Django 5.1.2 on 2024-11-22 20:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_orden_numero_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='orden',
            name='numero_recibo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
