# Generated by Django 4.2.3 on 2024-11-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
