# Generated by Django 4.2.3 on 2024-11-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='año',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='motor',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
