# Generated by Django 4.2.3 on 2024-11-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='disponible',
        ),
        migrations.AddField(
            model_name='producto',
            name='estatus',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_trato', 'En Trato'), ('vendido', 'Vendido')], default='disponible', max_length=10),
        ),
    ]
